const dataEvents = [
  {
    id: 1,
    title: "Stellar developer and protocol",
    date: "Thu, 22 Jan, 1:00",
    location: "Online",
    price: "Free",
    imageUrl: "/images/event1.png",
    category: "Tech",
  },
  {
    id: 2,
    title: "React Summit 2026",
    date: "Mon, 10 Feb, 9:00",
    location: "London",
    price: "49",
    imageUrl: "/images/event2.png",
    category: "Tech",
  },
  {
    id: 3,
    title: "2026 Wemabod Real Estate Outlook",
    date: "Wed, 5 Mar, 10:00",
    location: "Lagos",
    price: "Free",
    imageUrl: "/images/event3.png",
    category: "Party",
  },
  {
    id: 4,
    title: "Next.js Conf 2026",
    date: "Wed, 5 Mar, 10:00",
    location: "New York",
    price: "199",
    imageUrl: "/images/event4.png",
    category: "Tech",
  },
  {
    id: 5,
    title: "Consensus 2026",
    date: "Wed, 5 Mar, 10:00",
    location: "Online",
    price: "Free",
    imageUrl: "/images/event5.png",
    category: "Crypto",
  },
  {
    id: 6,
    title: "Asian Cuisine Festival",
    date: "Tue, 3 Feb, 9:00",
    location: "Singapore",
    price: "35",
    imageUrl: "/images/event6.png",
    category: "Food",
  },
  {
    id: 7,
    title: "Global Wellness Summit",
    date: "Thu, 12 Mar, 8:00",
    location: "Online",
    price: "99",
    imageUrl: "/images/event1.png",
    category: "Wellness",
  },
  {
    id: 8,
    title: "CrossFit Games Open 2026",
    date: "Mon, 15 Mar, 7:00",
    location: "London",
    price: "50",
    imageUrl: "/images/event2.png",
    category: "Gym",
  },
  {
    id: 9,
    title: "Interfaith Dialogue Conference",
    date: "Sun, 20 Apr, 10:00",
    location: "New York",
    price: "Free",
    imageUrl: "/images/event3.png",
    category: "Religion",
  },
  {
    id: 10,
    title: "Lagos Tech Fest",
    date: "Fri, 28 Feb, 9:00",
    location: "Lagos",
    price: "25",
    imageUrl: "/images/event4.png",
    category: "Tech",
  },
];
export { dataEvents };
